### PR TITLE
Packager Support for Linux and Mac OS X

### PR DESCRIPTION
**Pull request by NotDaveLane**
I've modified the packager to support execution on Linux and Mac OS X.  It fixes folder separators and file paths for non-Windows OSes.

Since Linux and Mac users won't be able to use the preverify tool currently included with the installer for "Command Line Tools for BlackBerry Smartphone Apps", I have also added support to BBWPProperties for a "preverify_directory" value (this should be the path to the directory which contains the preverify executable).

### CODE REVIEW

**Comment by filmaj** [comment]
thank you

**Comment by MartinMReed** [comment]
Why not use File.separator to avoid situations like this:

```
if( OperatingSystems.isWindows() ) {
  _rapc = _sessionHome + "\\" + _rapc;
}
else{
  _rapc = _sessionHome + "/" + _rapc;
}
```

**Comment by jasonschroeder** [comment]
Agree with @MartinMReed's comment.

**Comment by tneil** [comment]
Hi David,

I've attached this issue to the Golf milestone. We will be adding Mac support for the WebWorks Smartphone SDK and this code should come in handy

**Comment by aleksejspopovs** [comment]
I'm sorry if I'm wrong, but isn't Adobe AIR SDK required for the WebWorks packaging process? And, AFAIK, AIR SDK works only under Windows and Mac OS, so there's no point in porting the packager to Linux, unfortunately :(

**Comment by tneil** [comment]
For the PlayBook SDK we already support Mac/Windows but no Linux.  You are correct Alexey, the Tablet SDK is Mac and Windows, Adobe is dropping Linux support because of lack of demand vs cost of maintenance.

Currently our Smartphone SDK only runs on Windows, but we are now adding Mac support for the Smartphone SDK.

We will also ensure that the current /o style parameters will allow -o style parameters on Mac and Windows to be more cross platform compliant

**Comment by bert2002** [comment]
Looking forward for the Linux support. This will improve everything for me :)

**Comment by tneil** [comment]
@bert2002 We've indicated that we will be having Mac support.. but no Linux support for the SDK

**Comment by aleksejspopovs** [comment]
As I already said above, I'm pretty sure that Linux support isn't possible.

**Comment by bert2002** [comment]
ooohh right. Apparently I was too excited to read all comments. But at least Mac support will be added. Weill done.

**Comment by tneil** [comment]
Yup.. we'll have support for both Mac & Windows for:
- WebWorks SDK for Smartphones
- WebWorks SDK for Tablet OS
- Ripple Emulator

**Pull request closed without merging**
